// Generated by gencpp from file adaptive_clustering/ClusterArray.msg
// DO NOT EDIT!


#ifndef ADAPTIVE_CLUSTERING_MESSAGE_CLUSTERARRAY_H
#define ADAPTIVE_CLUSTERING_MESSAGE_CLUSTERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>

namespace adaptive_clustering
{
template <class ContainerAllocator>
struct ClusterArray_
{
  typedef ClusterArray_<ContainerAllocator> Type;

  ClusterArray_()
    : header()
    , clusters()  {
    }
  ClusterArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , clusters(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  _clusters_type;
  _clusters_type clusters;





  typedef boost::shared_ptr< ::adaptive_clustering::ClusterArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adaptive_clustering::ClusterArray_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterArray_

typedef ::adaptive_clustering::ClusterArray_<std::allocator<void> > ClusterArray;

typedef boost::shared_ptr< ::adaptive_clustering::ClusterArray > ClusterArrayPtr;
typedef boost::shared_ptr< ::adaptive_clustering::ClusterArray const> ClusterArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::adaptive_clustering::ClusterArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::adaptive_clustering::ClusterArray_<ContainerAllocator1> & lhs, const ::adaptive_clustering::ClusterArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.clusters == rhs.clusters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::adaptive_clustering::ClusterArray_<ContainerAllocator1> & lhs, const ::adaptive_clustering::ClusterArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace adaptive_clustering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adaptive_clustering::ClusterArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adaptive_clustering::ClusterArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adaptive_clustering::ClusterArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd09c173efb23a94da0f4821031bc47e";
  }

  static const char* value(const ::adaptive_clustering::ClusterArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd09c173efb23a94ULL;
  static const uint64_t static_value2 = 0xda0f4821031bc47eULL;
};

template<class ContainerAllocator>
struct DataType< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adaptive_clustering/ClusterArray";
  }

  static const char* value(const ::adaptive_clustering::ClusterArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"sensor_msgs/PointCloud2[] clusters\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::adaptive_clustering::ClusterArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.clusters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adaptive_clustering::ClusterArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::adaptive_clustering::ClusterArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "clusters[]" << std::endl;
    for (size_t i = 0; i < v.clusters.size(); ++i)
    {
      s << indent << "  clusters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.clusters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADAPTIVE_CLUSTERING_MESSAGE_CLUSTERARRAY_H
